Task24_Middle/Models/Answer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Middle.Models
{
    public class Answer : BaseEntity
    {
        public int UserId { get; set; }
        public int QuestionId { get; set; }
        public int QuestionnaireId { get; set; }
        public string AnswerText { get; set; }
        public virtual User User { get; set; }
        public virtual Question Question { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
    }
}

Task24_Middle/Models/Article.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Middle.Models
{
    public class Article : BaseEntity
    {
        public DateTime DateTimePosted { get; set; }
        public string Header { get; set; }
        public string SubHeader { get; set; }
        public string Text { get; set; }
    }
}

Task24_Middle/Models/BaseEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Middle.Models
{
    public class BaseEntity
    {
        public int Id { get; set; }
    }
}

Task24_Middle/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Middle.Models
{
    public class Comment : BaseEntity
    {
        public int UserId { get; set; }
        public DateTime DateTimeCommented { get; set; }
        public string Text { get; set; }
        public virtual User User{ get; set; }
    }
}

Task24_Middle/Models/Question.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Middle.Models
{
    public class Question : BaseEntity 
    {
        public string QuestionText { get; set; }
        public int QuestionTypeId { get; set; }
        public string AvailableAnswers { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
    }
}

Task24_Middle/Models/QuestionType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Middle.Models
{
    public class QuestionType : BaseEntity 
    {
        public string TypeName { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}

Task24_Middle/Models/Questionnaire.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Middle.Models
{
    public class Questionnaire : BaseEntity
    {
        public DateTime FilledDateTime { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
    }
}

Task24_Middle/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Middle.Models
{
    public class User : BaseEntity
    {
        public string Name { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
    }
}

Task24_Middle/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task24_Middle.Repositories;

namespace Task24_Middle.Controllers
{
    public class ArticleController : Controller
    {
        UnitOfWork unitOfWork;
        public ArticleController()
        {
            unitOfWork = new UnitOfWork();
        }

        public ActionResult ShowArticles()
        {
            return View(unitOfWork.ArticleRepository.GetAll());
        }
    }
}

Task24_Middle/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task24_Middle.Repositories;
using Task24_Middle.Models;

namespace Task24_Middle.Controllers
{
    public class CommentController : Controller
    {
        UnitOfWork unitOfWork;
        public CommentController()
        {
            unitOfWork = new UnitOfWork();
        }
        // GET: Comment
        public ActionResult ShowComments()
        {
            return View(unitOfWork.CommentRepository.GetAllWithRelated());
        }

        [HttpPost]
        public ActionResult ShowComments(FormCollection form)
        {
            string name = form.Get("username");
            User currentUser = unitOfWork.UserRepository.GetByName(name);
            if(currentUser == null)
            {
                currentUser = new User() { Name = name };
                unitOfWork.UserRepository.Add(currentUser);
                unitOfWork.Save();
            }

            string comment_text = form.Get("comment_text");
            Comment currentComment = new Comment()
            {
                Text = comment_text,
                DateTimeCommented = DateTime.Now,
                UserId = unitOfWork.UserRepository.GetByName(name).Id
            };

            unitOfWork.CommentRepository.Add(currentComment);
            unitOfWork.Save();
            return RedirectToAction("ShowComments");
        }
    }
}

Task24_Middle/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task24_Middle.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Task24_Middle/Controllers/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task24_Middle.Models;
using Task24_Middle.Repositories;

namespace Task24_Middle.Controllers
{
    public class QuestionnaireController : Controller
    {
        UnitOfWork unitOfWork;

        public QuestionnaireController()
        {
            unitOfWork = new UnitOfWork();
        }

        [HttpGet]
        public ActionResult ShowQuestions()
        {
            return View(unitOfWork.QuestionRepository.GetAllWithRelated());
        }

        [HttpPost]
        public ActionResult ShowResult(FormCollection form)
        {
            Questionnaire questionnaire = new Questionnaire()
            {
                FilledDateTime = DateTime.Now
            };
            unitOfWork.QuestionnaireRepository.Add(questionnaire);
            unitOfWork.Save();

            User user = unitOfWork.UserRepository.GetByName(form["username"]);
            if (form["username"] == String.Empty)
            {
                ModelState.AddModelError("username", "Please enter username");
            }
            if (user == null)
            {
                user = new User()
                {
                    Name = form["username"]
                };
                unitOfWork.UserRepository.Add(user);
                unitOfWork.Save();
            }

            foreach (var key in form.AllKeys)
            {
                if (key == "username") continue;
                Answer currentAnswer = new Answer()
                {
                    AnswerText = form[key],
                    QuestionnaireId = questionnaire.Id,
                    UserId = user.Id,
                    QuestionId = Convert.ToInt32(key.Split('_')[1]),
                };
                unitOfWork.AnswerRepository.Add(currentAnswer);
            }
            unitOfWork.Save();

            return View(unitOfWork.AnswerRepository.GetAllWithRelated());
        }
    }
}

Task24_Middle/Views/Article/ShowArticles.cshtml
@model IEnumerable<Task24_Middle.Models.Article>
@{
    ViewBag.Title = "ShowArticles";
}

@foreach(var article in Model)
 {
    <h1>@article.Header</h1>
    <h2>@article.DateTimePosted</h2>
    <h3>@article.SubHeader</h3>
    <p>@article.Text</p>
 }

Task24_Middle/Views/Comment/ShowComments.cshtml
@model IEnumerable<Task24_Middle.Models.Comment>
@{
    ViewBag.Title = "ShowComments";
}

<h2>ShowComments</h2>

<div class="comment_input_block">
    @using (Html.BeginForm(FormMethod.Post))
    {
        @Html.Label("Username: ");
        @Html.TextBox("username", String.Empty, new { @class = "username", required = "required" });
        @Html.Label("Comment: ");
        @Html.TextArea("comment_text", new { @class = "comment_text", required = "required" });
        <input class="comment_submit" type="submit" value="Submit" />
    }
</div>
<div class="comment_output_block">
    @foreach (var comment in Model)
    {
        <p>Username: @comment.User.Name</p>
        <p>Date & Time: @comment.DateTimeCommented</p>
        <p>Comment: @comment.Text</p>
        <hr />
    }
</div>

Task24_Middle/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Task24_Middle/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Task24_Middle/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Task24_Middle/Views/Questionnaire/ShowQuestions.cshtml
@model IEnumerable<Task24_Middle.Models.Question>
@{
    ViewBag.Title = "ShowQuestions";
}

<h2>ShowQuestions</h2>

@helper CheckBoxHelper(string[] words, int num)
{
    <ol>
        @foreach (string word in words)
        {
            <li>
                <input name="mult_@num" type="checkbox" value="@word" />
                <label for="@word">@word</label>
            </li>
        }
    </ol>
}

@helper RadioHelper(string[] words, int num)
{
    <ol>
        @foreach (string word in words)
        {
            <li>
                <input name="mult_@num" type="radio" value="@word" />
                <label for="@word">@word</label>
            </li>
        }
    </ol>
}

@using (Html.BeginForm("ShowResult", "Questionnaire", FormMethod.Post, new { @class = "questions" }))
{
    <h2>Enter Your Username: @Html.TextBox("username", String.Empty, new { required="required"} )</h2>
    foreach (var question in Model)
    {
        <div class="question_@question.Id">
            <p>Question #@question.Id</p>
            @Html.DisplayFor(modelItem => question.QuestionText)
            @if (question.QuestionType.TypeName == "checkbox")
            {
                @CheckBoxHelper(question.AvailableAnswers.Split(','), question.Id)
            }
            else if (question.QuestionType.TypeName == "radio")
            {
                @RadioHelper(question.AvailableAnswers.Split(','), question.Id)
            }
            else
            {
                @Html.TextBox($"text_{question.Id}", String.Empty, new { required = "required", placeholder = "Answer Question" })
            }
        </div>
    }
    <input class="submit_answers" type="submit" value="Submit Answers" />
}

Task24_Middle/Views/Questionnaire/ShowResult.cshtml
@model IEnumerable<Task24_Middle.Models.Answer>
@{
    ViewBag.Title = "ShowResult";
}

<h2>Thank you for participation, @Model.First().User.Name</h2>

@foreach(var answer in Model)
 {
    <p>Question: @answer.Question.QuestionText</p>
    <p>Your Answer: @answer.AnswerText</p>
    <hr />
 }

Task24_Middle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Task24_Middle/Views/Shared/_LibraryLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/LibraryStyle.css")" rel="stylesheet" type="text/css" />
    <title>Task24_Low</title>
</head>
<body>
    <header id="top">
        <h1>Task24_Low</h1>
    </header>
    <main>
        <div class="right_sidebar">
            <ul>
                <li>@Html.ActionLink("Articles", "ShowArticles", "Article")</li>
                <li>@Html.ActionLink("Comments", "ShowComments", "Comment")</li>
                <li>@Html.ActionLink("Questionnaire", "ShowQuestions", "Questionnaire")</li>
            </ul>
        </div>
        <div class="main_body">
            @RenderBody()
        </div>
    </main>
    <footer>
        <a href="#top">To the Top</a>
        <p>Ivan Chupryna, Some Email</p>
        <p>Copyright © 2021. Task24_Low.com</p>
    </footer>
</body>
</html>